---
# file: roles/metricbeat/tasks/main.yml
- name: register subscription and yum proxy setting
  include: yum_setup.yml

- block:
  - name: enable elastic repo
    copy: >
      src=elastic.repo
      dest=/etc/yum.repos.d/elastic.repo
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_elastic_repo_setting

  - name: metricbeat install
    package: name=metricbeat state=latest

  - name: metricbeat setting
    template: >
      src=metricbeat.yml.j2
      dest=/etc/metricbeat/metricbeat.yml
      owner=root
      group=root
      mode=0644
      backup=yes
    register: is_metricbeat_setting
    notify: metricbeat restart

  always:
  - name: metricbeat common backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_elastic_repo_setting|default() }}"
      - "{{ is_metricbeat_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable metricbeat service
  service: name=metricbeat state=started enabled=yes daemon_reload=yes
